### ISSUE TITLE
Not getting a functional avi file

### ISSUE THREAD

**Issue by a52siddi** [xmementoit/MJPEGDecoder#1]
Hello.

After running the following command:

`mjpegDecoder heli.mjpg giveme.avi`

images for each of the frames were generated but only an empty .avi file (giveme.avi) was produced. 

Running the command produced the following result on the command line:

`Segmentation fault (core dumped)`

When I open the avi file it just says "Stream contains no data". Why is the avi file empty?

Waiting eagerly for your response.

**Comment by DamZiobro** [comment]
Could you attach your heli.mjpg here and core file dumped while 'Segementation fault (core dumped)' is visible, please?

**Comment by a52siddi** [comment]
Thank you for the reply.

I have attached the file to this comment:

[heli.zip](https://github.com/xmementoit/MJPEGDecoder/files/836228/heli.zip)

I had to zip the file because I cannot attach .mjpg files directly to comments on github. 

I couldn't find the core file you asked about. Where can I find it? I am running the code on RHEL 6.6

Waiting eagerly for your response.

**Comment by DamZiobro** [comment]
core file is dumped in the dir where exec file is run from (in our case in the dir where mjpegDecoder is placed). 
However in order to unlock core file dumping you need to set core file limit to 'unlimited'. Use this command:
ulimit -c unlimited 

I was able to reproduce this issue and will provide fix soon

**Comment by DamZiobro** [comment]
One more tip for the future. 
If you will have core file dumped, you can run following command to get stack frames of all frames of the application in order to debug where the problem is:

echo "thread apply all bt" > commands && gdb -c core mjpegDecoder -x commands -batch

**Comment by DamZiobro** [comment]
Sorry for delay - forgot to do that earlier. I solved it today over lunch by this commit: 
https://github.com/xmementoit/MJPEGDecoder/commit/69105eed76b0076ab2ce2b5ac0b30e4fa4681a69
